### ISSUE TITLE
KeyError: 'frames'

### ISSUE THREAD

**Issue by hyping111** [SysCV/pcan#11]
**My purpose is to calculate the evaluation metrics in the paper，and I found instructions and codes for calculating Multi Object Tracking and Segmentation metrics on BDD100K's website(https://doc.bdd100k.com/evaluate.html#multi-object-tracking-and-segmentation-segmentation-tracking), when I run the following code to evaluate the algorithms with public annotations,**

python -m bdd100k.bdd100k.eval.run -t seg_track -g /home/dlz/pcan/data/bdd/labels/seg_track_20/seg_track_val_cocoformat.json -r /home/dlz/pcan/paintedimg.zip

**I got an error:**
Traceback (most recent call last):
  File "/home/dlz/anaconda3/envs/pcan/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dlz/anaconda3/envs/pcan/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dlz/PCAN/bdd100k/bdd100k/eval/run.py", line 319, in <module>
    run()
  File "/home/dlz/PCAN/bdd100k/bdd100k/eval/run.py", line 292, in run
    args.gt, args.result, bdd100k_config, args.nproc
  File "/home/dlz/PCAN/bdd100k/bdd100k/eval/run.py", line 226, in _load_frames
    gt_frames = bdd100k_to_scalabel(load(gt_base, nproc).frames, config)
  File "/home/dlz/PCAN/scalabel/scalabel/label/io.py", line 90, in load
    ret_cfg = process_file(inputs)
  File "/home/dlz/PCAN/scalabel/scalabel/label/io.py", line 77, in process_file
    raw_frames.extend(content["frames"])
KeyError: 'frames'

**The real data I passed in is the seg_track_val_cocoformat.json file, and I found that the raw_frames and raw_cfg(config) parameters required by the code are not given in the file. Does the ground-truth JSON file need further processing?How to solve this problem? Thanks for your answer!**

**Comment by lkeab** [comment]
Yes. It needs further data format conversion. Please refer to the instructions [here](https://github.com/SysCV/pcan/blob/main/docs/GET_STARTED.md#conversion-to-the-bdd100kscalabel-format-and-evalution) on further data format conversion, where this [script](https://github.com/SysCV/pcan/blob/main/scripts/convert_to_bdd.sh) helps you converting result from coco to bdd format. Then, after conversion, please refer to this [script](https://github.com/SysCV/pcan/blob/main/scripts/eval_bdd_submit.sh) on evaluating the final performance on validation set or directly submitting to the leader board.
