### ISSUE TITLE
Visualization Script

### ISSUE THREAD

**Issue by rahul1801** [SysCV/pcan#14]
Thank you for the great work!

I actually have a custom dataset on which I would like to create MOTS visualizations. Additionally, I would like to perform performance evaluations (for the MOTS task) on my dataset.

Can you let me know if a script is available to directly create visualizations on a set of images? Also, can you provide a brief description of how custom datasets need to be prepared, to run the MOTS scripts? Thanks in advance!

**Comment by lkeab** [comment]
hi, we provided the visual script [here](https://github.com/SysCV/pcan/blob/main/docs/GET_STARTED.md#visualization-script).

**Comment by rahul1801** [comment]
Hi, I tried running the viz script and I get the following error:

FileNotFoundError: [Errno 2] No such file or directory: 'data/bdd/images/seg_track_20/val/b1c66a42-6f7d68ca/b1c66a42-6f7d68ca-0000001.jpg'

I placed all my images in the following path: **data/bdd/images/seg_track_20/val**. My image names follow the convention: <number>.png. Maybe I am missing out on something here, but from the looks of it, I feel that even the file names of the custom dataset need to exactly match with BDD100K. Can you help me out here? 

Thanks.

**Comment by lkeab** [comment]
I think you could modify the file names in the validation json
