### ISSUE TITLE
May I ask whether your team has successfully delivered the article about VIS task in ECCV2022

### ISSUE THREAD

**Issue by fxooooooooo** [SysCV/pcan#21]

**Comment by lkeab** [comment]
Our paper is accepted in NeurIPS 21 not eccv22.

**Comment by fxooooooooo** [comment]
> Our paper is accepted in NeurIPS 21 not eccv22.

Sorry！Will your code on the VIS part be open source？

**Comment by lkeab** [comment]
You can refer to the implementation of our mask head. The main differences are data loader and object detector. Also, we will release a stronger model of VIS [in this repo](https://github.com/SysCV/vmt) soon.

**Comment by fxooooooooo** [comment]
> You can refer to the core implementation of our mask head. The main differences are data loader and object detector. Also, we will release a stronger model of VIS [in this repo](https://github.com/SysCV/vmt) soon.

ok! Thank you very much for your work!
