### ISSUE TITLE
The time it takes to train the model?

### ISSUE THREAD

**Issue by f414158949** [SysCV/pcan#22]
In your paper, I find "Our model is trained with initial learning rate 0.0025 on 4 GPUs using SGD, and executes with a speed of 15.0 FPS on ResNet-50.". and could you tell me the type of GPU and the time it takes to train the PCAN model on the BDD100K segmentation tracking dataset? (Using the the initial model weights from BDD100k MOT tracking set and not using the the initial model weights) thanks

**Comment by lkeab** [comment]
RTX gpu and less than 5 hours (in my impression)
