### ISSUE TITLE
unexpected result on our own street survelliance data

### ISSUE THREAD

**Issue by SRainGit** [SysCV/pcan#3]
Hi, thanks for your great work!
I tried the pretrained models on `BDD100K seg_track val`set, the reuslts are the same with the demos.
But on our own videos (static cameras, 2560x1440), the detected objects are not enough. And some cars only got part bounded.
![00000145](https://user-images.githubusercontent.com/44186254/147203243-f28fb3eb-0e42-441d-a3d6-a21bb5c7d614.png)
![00000000](https://user-images.githubusercontent.com/44186254/147204215-132e09cf-0d1f-462c-9328-3c27ff89ff8e.png)
Is it just because the trained bdd dataset is different from our own data?
Do you have other preptrained models which is suitable for this kind of city street survelliance videos?
By the way, I don't know what is the difference between `pcan_pretrained_model.pth` and 'segtrack-fixed-new.pth' but they seem perform similar results. Thanks!

**Comment by lkeab** [comment]
I suggest you to retrain the model based on you images because the two datasets have very different angles when taking photos. 'pcan_pretrained_model.pth' is the final model of BDD100K MOTS while 'segtrack-fixed-new.pth' is the initial model weights trained on BDD100k MOT tracking set.

**Comment by changtimwu** [comment]
@SRainGit  Interesting application!   Based on my experience, doing object detection in a bird-eye view video is very challenging.  You better transform the picture's angle a bit before inference.    At evaluation stage, I would feed these samples into a typical object detection network and see if interested objects could be effective recognized.  

Another challenge is that in your sample pics, there are lots of cargo tricycles, which is quite common in China cities.  Unfortunately, this is not even a category in most public datasets.
