### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by xulinxulin** [SysCV/pcan#6]
dear author , this error occurred when I used the model you pprovided . 

_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

How should I solve it . What other models can I use.

**Comment by lkeab** [comment]
Hi, could you describe the errors in details with short-cut figures or more error information? I have not encountered this error before.

**Comment by xulinxulin** [comment]
> 
Hi,Unzip Your provided pretrained model will obtain a archive file,which cotain a data.pkl, when i use this .pkl file,occurred this error, it means that torch cannot read the .pkl file ,but when use the resnet50-19c8e357.pth to run tool/train.py without error.How should i use the archive folder.

**Comment by lkeab** [comment]
Hi, [this](https://hkustconnect-my.sharepoint.com/:u:/g/personal/lkeab_connect_ust_hk/EVdSxsVuKlFDg5I77VsFr4UB_KJQY4Dd_5ZUMJ6gG9A2Hw?e=IhqrfY) is a .pth file for model weight. There is no .pkl file.

**Comment by xulinxulin** [comment]
> Hi, [this](https://hkustconnect-my.sharepoint.com/:u:/g/personal/lkeab_connect_ust_hk/EVdSxsVuKlFDg5I77VsFr4UB_KJQY4Dd_5ZUMJ6gG9A2Hw?e=IhqrfY) is a .pth file for model weight. There is no .pkl file.

Thank you! My negligence and lack of knowledge led to this mistake. I solved the error under your guidance.
