### ISSUE TITLE
cannot import name 'NPROC' from 'scalabel.common.parallel'

### ISSUE THREAD

**Issue by ZhiCheng-H** [SysCV/pcan#7]
Hey there!
While running the script to convert the annotation from bdd100k format to COCO the following exception is being raised. cannot import name 'NPROC' from 'scalabel.common.parallel'. What is the possible solution for the problem?

**Comment by fyu** [comment]
It may be solved with installing the scalabel package with `pip install -U git+https://github.com/scalabel/scalabel.git`

**Comment by ZhiCheng-H** [comment]
Thanks for your suggestion. The problem has been solved. Maybe there is a problem with the scalabel installation package on the pypi platform.
